import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#FFFFFF]'>{children}</body>
    </html>
  )
}


//bg-gradient-to-r from-[#FAFBFF] to-[#F3F4F8]