import "./globals.css";
import Provider from "./provider";
import { Poppins } from "next/font/google";
import { Inter } from "next/font/google";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${poppins.className} overflow-y-scroll`}>
        {children}
      </body>
    </html>
  );
}

//bg-gradient-to-r from-[#FAFBFF] to-[#F3F4F8]
